### ISSUE TITLE
Error sending using "fcmRegistrationIDs"

### ISSUE THREAD

**Issue by bitc** [Holmusk/fcm-client#3]
There is a bug with generating the JSON request of the field [`fcmRegistrationIDs`](http://hackage.haskell.org/package/fcm-client-0.1.0.0/docs/FCMClient-JSON-Types.html#v:fcmRegistrationIDs)

**Bug**: It serializes to JSON field name: `"registration_i_ds"` (Instead of `"registration_ids"`)

This causes the FCM HTTP request to fail with error:

    FCMErrorResponseInvalidJSON {_fcmErrorMessage = "to\n"}

(Because the FCM server expects a JSON object either with a value for "to" or a value for "registration_ids", and we gave neither, so it defaults to reporting missing "to" field)

I am using [Aeson 1.4.2.0](http://hackage.haskell.org/package/aeson-1.4.2.0)

**Comment by bitc** [comment]
Here is a workaround:

```haskell
import Data.Aeson (Value(Object), toJSON)
import FCMClient
import FCMClient.JSON.Types
import qualified Data.HashMap.Strict as HashMap

repairFCMMessage :: FCMMessage -> Value
repairFCMMessage msg =
    let val = toJSON msg
    in case val of
        Object hm -> case HashMap.lookup "registration_i_ds" hm of
            Nothing -> val
            Just regIds -> Object $
                HashMap.insert "registration_ids" regIds
                    (HashMap.delete "registration_i_ds" hm)
        _ -> error $ "FCMMessage is not an Object: " ++ show val
```

And then use it like this:

```haskell
test :: ByteString -> FCMMessage -> IO ()
test authKey msg = do
    r <- fcmCallJSON authKey (repairFCMMessage msg)
    print r
```

**Comment by chshersh** [comment]
@bitc Thanks for reporting this issue! This is an unfortunate bug. It happens because custom `aeson` options are used to automatically generate instances from data types. And because the corresponding field has name `_fcmRegistrationIDs` it gots translated to wrong JSON.

https://github.com/Holmusk/fcm-client/blob/e8735c8029251d9610009d80309a1855e7f9b6ab/src/FCMClient/JSON/Types.hs#L209

It should be `_fcmRegistrationIds` instead. Would you care to open a PR? :slightly_smiling_face:

**Comment by bitc** [comment]
@chshersh I have created pull request #5 that fixes this bug, and tested that it works.
(btw, please also take a look at my other pull requests and merge if possible)

**Comment by chshersh** [comment]
@bitc Thanks for your effort so far! I'm on vacation at the moment, will look at all opened PRs after.
